// <auto-generated />
namespace SchoolApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DescricaoNoTurno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DescricaoNoTurno));
        
        string IMigrationMetadata.Id
        {
            get { return "201812071135225_DescricaoNoTurno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
